# Bug 5: when calling super after a call, super target is wrong

default: test

targets:

  foo:
    steps:
    - print: "Foo"

  test:
    steps:
    - call: foo
    - super:
